services:
  - type: web
    name: vinus-backend
    runtime: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: TU_URL_DE_NEON_AQUI
      - key: SPRING_DATASOURCE_USERNAME
        value: TU_USUARIO_DE_NEON_AQUI
      - key: SPRING_DATASOURCE_PASSWORD
        value: TU_CONTRASEÑA_DE_NEON_AQUI